# Generated by Django 4.2.2 on 2023-06-13 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_alter_course_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='Student',
            field=models.ManyToManyField(blank=True, to='school.student'),
        ),
        migrations.AlterField(
            model_name='course',
            name='Teacher',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='school.teacher'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='Course',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='school.course'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='Student',
            field=models.ManyToManyField(blank=True, to='school.student'),
        ),
    ]
