# Generated by Django 4.2.2 on 2023-06-13 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_alter_course_student_alter_course_teacher_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='Teacher',
        ),
        migrations.AlterField(
            model_name='course',
            name='Student',
            field=models.ManyToManyField(to='school.student'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='Course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.course'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='Student',
            field=models.ManyToManyField(to='school.student'),
        ),
    ]
