# Generated by Django 4.2.2 on 2023-06-13 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_remove_course_teacher_alter_course_student_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='Student',
        ),
    ]
