# Generated by Django 4.2.2 on 2023-06-13 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_alter_teacher_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='Course',
        ),
        migrations.AddField(
            model_name='course',
            name='Teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='school.teacher'),
        ),
    ]
